# Generated by Django 3.1.2 on 2020-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0009_auto_20201120_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
